### ISSUE TITLE
I propose to do the merge with last blender 2.79b sources

### ISSUE THREAD

**Issue by youle31** [bge-community/Ketsji-Game-Engine#11]
hey, this is youle. If you need help with git, tell me.
I can do a video conference to show if needed

**Comment by marechal-p** [comment]
Thanks for the help Youle !
I might give it a try this WE unless someone wants to do it before :)
Is there a way to reach you if we want to ask some questions or anything ?

**Comment by youle31** [comment]
Hello, I propose to do it myself or help to do it if someone has difficulties with (I already tested it and it's a bit tricky I guess if you're not familiar with git and meld (program to solve conflicts)). I can be contacted @you.le@live.fr
Sorry about my bad trip on BA. All frogs are not like me :P

**Comment by trevortomesh** [comment]
I support this. Can we get a pull request?

**Comment by marechal-p** [comment]
The pull request is usually done once something is finished.

**Comment by youle31** [comment]
I redo this and do a pull request so.

**Comment by youle31** [comment]
In fact I never did a pull request before but it seems we need to upload our local sources on the net. So here is a .diff:

https://drive.google.com/file/d/1HsVy5gyyrhr-xP_Xc64ur2UrME86f2l3/view?usp=sharing

I use Tortoise git on Windows to apply.

(Merge process is very quick but I tested it only on windows with 1 BGMC game (city of time) and I don't know if there will be bugs caused by the merge. You can tell me if there is an issue)

**Comment by youle31** [comment]
I'll try to quickly explain how we do:

1) We add a remote branch with BF blender sources:
git remote add aNameIChooseForMyRemoteBranch ../BFBlenderSources
2) We update the remote branch:
git remote update
3) We merge the master from remote branch:
git merge aNameIChooseForMyRemoteBranch/master
4) The merge will fail because as there are few months upbge has not been updated there will be conflicts in the code. So we have to solve these conflicts with a program named meld. To install, there are tutorials on the net.
git mergetool
5) We use meld to solve conflicts:
there are 3 columns:
- On the left you have your local sources before the merge
- on the right you have the sources from remote branch
- on the middle there is the result of the merge (Fusion)
- As we use upbge and that official bge is not update since a while, for each gameengine file with a merge conflict, we'll keep upbge sources (So in meld we do: changes > merge from left). If there is red in meld for a gameengine file, we keep the upbge sources so in most cases we put the left column red underlined code to the middle column. If this is not a gameengine file, we do changes > merge all
- When you solved all conflicts with meld, you try to compile. If there are compilation errors, you fix it manually. For example, here DNA_object_force.h has been renamed DNA_object_force_types.h so you rename when this is needed.
5) Once the compilation is ok, you have to test it with some files (I generally test it with BGMC files). Here I only quickly tested it with City of Time.
6) If all is right you commit your merge:
git commit
7) you clean the conflicting saved files:
git clean -fd
8) you add the files with solved conflicts to your merge commit:
git add .
9) you amend your merge commit with the last changes added:
git commit --amend
10) Then you can push to your git repo.

This is hard to explain, this is why I proposed (still propose) a video conference.
(this is my way to do with git, I have no idea if this is conventional, but this is how I do)

**Comment by marechal-p** [comment]
You could do a Youtube video, it helps when people are all around the world :P
Thanks for this Yul !

**Comment by youle31** [comment]
I'd prefer to do a team viewer. Because it might be take 1 hour (taking into account compil time...) and i couldn't answer eventual questions. I can do that when you want. On my computer. You'll see what i do and you can record if you want. Text tchat only because i don't really like to speak english

**Comment by youle31** [comment]
I'll join #upbgeusers irc if you want to talk with me

**Comment by trevortomesh** [comment]
Thanks, youle! Finding a time that works for everyone is the most difficult part.

**Comment by PeterBluewin** [comment]
I wonder if this branch will hold. We're waiting now. If it is clear whether BF does not prevent further development, one can also get involved. I wish you good luck.

**Comment by trevortomesh** [comment]
BF can't prevent further development -- that's the point of open source. Alos, we've got youle.

**Comment by marechal-p** [comment]
`BF can't prevent further development` yes they can, by simply stopping developping, with nobody to develop in place, they will actually manage to do it. It might be my pessimistic side, but Youle is proposing his help, and we should not abuse it. I am currently not able to name 1 developer for this fork, yet.

**Comment by trevortomesh** [comment]
We're still in the recruitment phase -- it's only been a few days since this fork came into being and we've already managed to piss a lot of people off. So -- I'd say we're doing pretty well.

**Comment by youle31** [comment]
Hello, I don't think BF has any intention to prevent any development in 2.7 neither in 2.8. In fact, I think this is the contrary (because it is open sources so they can get the work which interest them). The thing is that they didn't really want to be involved in 2.7 BGE development because of code design issues and because people who are paying BF developers are animation studios mainly. This is understandable from a point of view (even if I think that some bge developments could have benefit to animation studios because game development is continuously the quest of better performances, and Blender in general is stronger as All in 1 software, and can benefit from community ideas and involvment in Blender). It's a cool initiative if you manage to get "very involved" guys (because it requires a strong personal investissement) to learn BGE sources. I can try to help a bit (to transmit the few I know) if there are motivated people, but I'm personally tired and sick, so I can't be 100% involved. Anyway, feel free to ask me some questions if needed (about git, or general advices to begin) and I'll see if I can do something.

About 2.8, it is not possible to keep bge in its current state because BGE code depends on viewport code for many things. The work I did to adapt bge to 2.8 viewport could be continued, but this would need a big work, and if I rallied interactive mode idea, it is partly because I thought that in a "very" long term perspective, using Blender code will offer a very big power to Blender, which can benefit to all Blender users (including game makers). I'm talking about using all what we can do with bpy to create games or other content. So removing bge means: we rewrite part of things from scratch with a new design, we break things and try to do better to avoid some duplicated code.

Unfortunately, many things are lost for now. There won't be any backward compatibility but anyway, TOTAL backward compatibility would have been impossible technically with the new viewport. Many resources, tutorials, games won't be 2.8 compatible. And many other things won't be possible for now. 

From a coding point of view, this can be justified because important parts of bge code are old even if panzergame (Tristan) modernized it a lot. But it will need a very long time before interactive mode really looks like a True game engine, and I don't really know if they really want to give Blender a "True" game engine design for now. But it seems to me that it is the normal sense of the evolution that Blender, with time, becomes a big 3D all in 1 and competitive software, with "a kindof or a True game engine". This might be damagable for other open sources engines and I guess that the fact Blender patrons are more interested in animation side + the fact that they want to keep good partnership (don't really know what are the collaboration relations...) with foss and even with Unity or Unreal can make the process slower.

But as interactive mode main targets have been defined (visual logic, python API, export as exe, physics), it seemed to me that we'll have the possibility to create games. We can't be too much exigent for now because these targets will require hard work from BF coders (who are much more experienced than me or Tristan even if Tristan is really really talented). And if Blender has good opportunities to have good developments on game side one day, I think this is in Blender interest to get it, except that it might generate tensions with partners (concurrency).

After, I'm not a "medium" and all of this is just speculations.

**Comment by youle31** [comment]
well I did a git repo https://github.com/youle31/Ketsji-help/compare/https://github.com/bge-community/Ketsji-Game-Engine...youle31:master and the last commit is the merge commit. No idea how to do a pull request so if you're interested, you can pick the last commit

**Comment by trevortomesh** [comment]
Sir, you are a god among men. :-D

**Comment by marechal-p** [comment]
Merge is done at https://github.com/youle31/Ketsji-help
