### ISSUE TITLE
Document MacOSX setup

### ISSUE THREAD

**Issue by DctrBinary** [bge-community/Ketsji-Game-Engine#21]
I'm currently working on figuring this part out. So far I have tried a pure clone of the project and the  normal process for building blender. Right now I am getting weird errors with Malloc.

**Comment by youle31** [comment]
Hello, if you have a MAC computer, XCode, git... and team viewer installed, I can try to help you to build ketsji/upbge with distant access. I already did it 1 time a long time ago (for 0.1.0 on a friend's MAC) and it was working. I don't really know if 0.2.3 will work but worth to try.

You can also try to build this repo: https://github.com/youle31/Ketsji-help (same than ketsji but with commits imported from Blender to update what is outside gameengine folder) and maybe you will have more luck.
Else you can also try the options specific to upbge on linux: https://github.com/UPBGE/blender/wiki/Build-UPBGE-on-Linux (check with CXX11 in advanced cmake options)
If you can't have a full build you can try:

make lite

to build

Feel free to ask questions if I can help.

**Comment by marechal-p** [comment]
I built and tried your merge by the way, it works like a charm ! A few hours before you shipped it I was trying my hand on it, ran a `git rebase -i xxx` on Blender's master but I had to restart multiple times because I didn't know what to keep or not. Long story short what you did is great !

I did not merge on Ketsji because I was waiting for someone else to do it, so that they can learn from it (just pulling from your repo, building it to test, and then making a PR on Ketsji).

Hopefully they will get time to try in a week or two :)

**Comment by youle31** [comment]
hi, ok, great that 0.2.3 is still working on MACOSX too :)

(About git merge, this one was a bit hard but I think the next will be easier as blender 2.79 won't be developped indefinitely. Anyway, feel free to ask help about git if you need it another time)

**Comment by DctrBinary** [comment]
I'm getting farther along.  Now I have an assortment of buildtime errors:

all of them occur in utilities.h;

most are: call to 'abs' is ambiguous
and one is: use of undeclared identifier 'aligned_alloc'

**Comment by youle31** [comment]
@DctrBinary : hi, in cmake advanced options, did you check WITH_CXX11 ? I think it is not checked by default.

**Comment by DctrBinary** [comment]
I thought I did, but I might have checked for C++11 which was checked
already.

**Comment by DctrBinary** [comment]
Yes, with_cxx was checked.

**Comment by youle31** [comment]
Ok, in this case I fear I can't help. You can maybe try to find MAC users on #blendercoders IRC to ask or see if there is a troobleshooting section for blender compiling on MAC or see if there are related topics on the net. If Blender compilation is ok but not UPBGE you can try to git checkout an old UPBGE version to compile it... At least I know I managed to compile 0.1.0 some time ago. Good luck

**Comment by DctrBinary** [comment]
Thanks, and no worries, I appreciate it dude. I'm sure I'll get it sooner
or later.

For the record I had the same issue when I tried to build vanilla blender
as a sanity check.

**Comment by shuvit-game** [comment]
Thanks for working on this btw. I am eagerly watching your progress. I'd like to see how a mac build of my game works out.

**Comment by DctrBinary** [comment]
Success! It turns out that the issue is that OSX (clang) uses an ancient
version of the C library, so the above symbols are not recognized. So I
hackishly changed a couple lines in order to override this. Namely:
1(call to abs is ambiguous): #include <cstdlib> at the top of the file and
remove std:: from before each abs call.
2(use of unidentified alligned_alloc): comment out elif defined(__GNUC__)
and return statement and let it fall back on the else clause following it.

Thanks for the help guys. I'll write up a step by step for people who want
to build on OSX and eventually create a dmg when we have a release version.

**Comment by DctrBinary** [comment]
I don't have write access to this repository, so at the moment I am unable to push my local branch. Could one if the leaders update my prrmissions?

**Comment by DctrBinary** [comment]
Awesome, thanks guys.  I've created the branch to host the MacOSX build, and a pull request to close this issue.

**Comment by marechal-p** [comment]
https://github.com/bge-community/Ketsji-Game-Engine/pull/23 merged.
